[package]
name = "kotonoha-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "kotonoha"
path = "src/main.rs"

[dependencies]
kotonoha = { workspace = true }
hasami = { workspace = true, features = ["build"] }
clap = { workspace = true }
serde_json = { workspace = true }
